### PR TITLE
Import grains formula

### PR DESCRIPTION
**Pull request by tacerus**

### CODE REVIEW

**Comment by cboltz** [comment]
I'd prefer the original date (2017) for the first two commits.

Besides that, everything looks good.

**Comment by tacerus** [comment]
This has been imported using the same routine. The author dates are correct, just the GitHub UI does not display them - `git log` however, does:

```
git log --format=medium HEAD~2|head -n11
commit dd779268a9cec9905d56013b1ebe2fec0eb587d6
Author: Theo Chatzimichos <tampakrap@gmail.com>
Date:   Tue Jan 3 15:08:16 2017 +0100

    doc typo

commit 5dac703d1bd4e7033ce2c28fe889ef1f52f4e0c0
Author: Theo Chatzimichos <tampakrap@gmail.com>
Date:   Tue Jan 3 15:05:08 2017 +0100

    Initial commit
```

**Comment by tacerus** [comment]
To satisfy the GitHub experience the only option is to rewrite the commit dates, which in return fools someone checking when the import happened on the command line ...

**Comment by cboltz** [comment]
Indeed, checking locally shows that it's the same github issue as in PR 6. Therefore ignore my comment, and feel free to merge ;-)

**Pull request merged**
