### PR TITLE
rebootmgr: repair configuration for Tumbleweed

### PR DESCRIPTION
**Pull request by tacerus**
On Tumbleweed systems the configuration file placed using the formula
code was missing the "[rebootmgr]" header, causing options to be ignored.
This issue only affects Tumbleweed, where no /etc/rebootmgr.conf file
is provided by the package in favor of the one in /usr/etc. On Leap,
the package provides the file under /etc including the necessary section
header.
To resolve this problemtic discrepancy as well as to simplify the logic,
this refactors the handling to a simple file.managed state containing both
the common and the section header along with the configuration options.
This will ensure a uniform and functional file across both Leap and
Tumbleweed systems.

### CODE REVIEW

**Comment by cboltz** [comment]
Just wondering - this looks like you are re-inventing the wheel ^W https://docs.saltproject.io/en/latest/ref/states/all/salt.states.ini_manage.html

Is there a specific reason not to use ini_manage?

**Comment by tacerus** [comment]
Hi,
we are using ini_manage in other places, but here I did not realize it could be used. Is the configuration of rebootmgr really in ini format?
I don't find any ini parsing in https://github.com/search?q=repo%3ASUSE%2Frebootmgr+ini&type=code.

**Comment by tacerus** [comment]
Given that even if it is valid .ini it would require an additional file.prepend state to manage the header comment, I think we should keep file.managed.

**Comment by cboltz** [comment]
It looks like an ini file, and it smells like an ini file, so... ;-)

I understand the need for a file.prepend is slightly annoying, but IMHO that would still be better than a self-made ini_manage.

This is more an opinion than an objection, so if you really think the current code is better, feel free to merge.

**Comment by tacerus** [comment]
OK, added a commit.

**Pull request merged**
